F#src5190 add cpp wait for param
shadow-robot/common_resources pull request #140
Opened 2020-11-02 09:20 UTC by giusebar

## Proposed changes

Please explain the changes you made. Add pictures or videos to explain them better if appropiate.

## Types of changes

What types of changes does your code introduce?

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

Put an x in the boxes that apply. You can also fill these out after creating the PR. This is a reminder of what we should look for before merging this code. I have:

- [ ] Read and follow the [contributing guidelines](https://github.com/shadow-robot/sr_documentation/blob/master/CONTRIBUTING.md).
- [ ] Checked that all tests pass with my changes
- [ ] Added tests (automatic or manual) that prove the fix is effective or that the feature works
- [ ] Added necessary documentation (if appropriate)
- [ ] Added the corresponding license to each file and add the current year of any one that you modified.
- [ ] Tested on real hardware (if appropriate)

2020-11-03 13:17 UTC, ToivoS approved these changes

2020-11-04 09:23 UTC, mikramarc requested changes

2020-11-04 09:23 UTC, mikramarc commented on sr_utilities_common/include/sr_utilities_common/wait_for_param.h
> +* Copyright (C) 2019 Shadow Robot Company Ltd - All Rights Reserved. Proprietary and Confidential.
date, and its public

2020-11-04 09:23 UTC, mikramarc commented on sr_utilities_common/README.md
> +- timeout: after how long the script should give up waiting for the required conditions. If not set the script will wait forever for the condition to be met.
```suggestion
- timeout: after how long the script should give up waiting for the required conditions. If not set or set to zero or less, the script will wait indefinitely for the condition to be met.
```

2020-11-04 09:23 UTC, mikramarc commented on sr_utilities_common/scripts/sr_utilities_common/conditional_delayed_rostool.py
> +        if timeout > 0:
if timeout <= 0:
    continue

? would avoid nesting

2020-11-04 09:48 UTC, giusebar commented on sr_utilities_common/include/sr_utilities_common/wait_for_param.h
> +* Copyright (C) 2019 Shadow Robot Company Ltd - All Rights Reserved. Proprietary and Confidential.
wait i had fixed that

2020-11-04 09:49 UTC, mikramarc commented on sr_utilities_common/include/sr_utilities_common/wait_for_param.h
> +* Copyright (C) 2019 Shadow Robot Company Ltd - All Rights Reserved. Proprietary and Confidential.
ye, outdated

2020-11-04 12:28 UTC, mikramarc approved these changes

2020-11-04 13:53 UTC, merged