SRC-6418  Noetic migration 2 of 2
shadow-robot/common_resources pull request #168
Opened 2021-05-06 15:28 UTC by maxzieba

## Proposed changes

User Story: https://shadowrobot.atlassian.net/browse/SRC-6418
Migrating to noetic

## Checklist

If the task is applicable to this pull request (see applicability criteria in brackets), make sure it is completed before checking the corresponding box. Otherwise, tick the box right away. Make sure that **ALL** boxes are checked **BEFORE** the PR is merged.

- [ ] Manually tested that added code works as intended (if any functional/runnable code is added).
- [ ] Added automated tests (if a new class is added (Python or C++), interface of that class must be unit tested).
- [ ] Tested on real hardware (if the changed or added code is used with the real hardware).
- [ ] Added documentation (For any new feature, explain what it does and how to use it. Write the documentation in a relevant space, e.g. Github, Confluence, etc.)

2021-05-07 08:15 UTC, biofotis requested changes

2021-05-07 08:15 UTC, biofotis commented on sr_speech_control/src/sr_speech_control/speech_control.py
> +#!/usr/bin/env python
should we specify python3?

2021-05-07 08:15 UTC, biofotis commented on sr_utilities_common/src/sr_utilities_common/aws_manager.py
> +#!/usr/bin/env python
here as well

2021-05-07 08:15 UTC, biofotis commented on sr_utilities_common/test/aws_manager_test.py
> +#!/usr/bin/python
and here

2021-05-07 08:15 UTC, biofotis commented on sr_wear_logger/CMakeLists.txt
> +   DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION}
how about the launch file?

2021-05-07 08:15 UTC, biofotis commented on sr_wear_logger/src/sr_wear_logger/dummy_publisher.py
> +#!/usr/bin/env python
python3?

2021-05-07 08:15 UTC, biofotis commented on sr_wear_logger/src/sr_wear_logger/sr_wear_logger.py
> +#!/usr/bin/env python
as well

2021-05-07 08:15 UTC, biofotis commented on sr_wear_logger/test/test_sr_wear_logger.py
> +#!/usr/bin/python
here too

2021-05-07 08:32 UTC, maxzieba commented on sr_wear_logger/src/sr_wear_logger/sr_wear_logger.py
> +#!/usr/bin/env python
Corrected

2021-05-07 08:32 UTC, maxzieba commented on sr_wear_logger/test/test_sr_wear_logger.py
> +#!/usr/bin/python
Corrected

2021-05-07 08:32 UTC, maxzieba commented on sr_wear_logger/src/sr_wear_logger/dummy_publisher.py
> +#!/usr/bin/env python
Corrected

2021-05-07 08:32 UTC, maxzieba commented on sr_utilities_common/test/aws_manager_test.py
> +#!/usr/bin/python
Corrected

2021-05-07 08:32 UTC, maxzieba commented on sr_utilities_common/src/sr_utilities_common/aws_manager.py
> +#!/usr/bin/env python
Corrected

2021-05-07 08:32 UTC, maxzieba commented on sr_speech_control/src/sr_speech_control/speech_control.py
> +#!/usr/bin/env python
Corrected

2021-05-07 08:33 UTC, maxzieba commented on sr_wear_logger/CMakeLists.txt
> +   DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION}
Added

2021-05-10 16:29 UTC, biofotis approved these changes

2021-05-10 16:39 UTC, giusebar approved these changes

2021-05-10 16:40 UTC, merged