Src 6413 create a collision model for the rack
shadow-robot/common_resources pull request #175
Opened 2021-05-18 09:17 UTC by maxzieba

## Proposed changes

Please explain the changes you made. Add pictures or videos to explain them better if appropriate.

## Checklist

If the task is applicable to this pull request (see applicability criteria in brackets), make sure it is completed before checking the corresponding box. Otherwise, tick the box right away. Make sure that **ALL** boxes are checked **BEFORE** the PR is merged.

- [ ] Manually tested that added code works as intended (if any functional/runnable code is added).
- [ ] Added automated tests (if a new class is added (Python or C++), interface of that class must be unit tested).
- [ ] Tested on real hardware (if the changed or added code is used with the real hardware).
- [ ] Added documentation (For any new feature, explain what it does and how to use it. Write the documentation in a relevant space, e.g. Github, Confluence, etc.)

2021-05-18 10:29 UTC, giusebar requested changes
Missing scene file

2021-05-18 10:59 UTC, beatrizleon commented on sr_description_common/models/server_rack/model.sdf
> +
remove this line

2021-05-18 11:00 UTC, beatrizleon commented on sr_description_common/models/server_rack/model.sdf
> +
here again

2021-05-18 11:02 UTC, beatrizleon commented on sr_description_common/models/server_rack/model.sdf
> +</sdf>
add empty line at end of file

2021-05-18 12:35 UTC, maxzieba commented on sr_description_common/models/server_rack/model.sdf
> +</sdf>
Added

2021-05-18 12:35 UTC, maxzieba commented on sr_description_common/models/server_rack/model.sdf
> +
Removed

2021-05-18 12:35 UTC, maxzieba commented on sr_description_common/models/server_rack/model.sdf
> +
Removed

2021-05-18 14:48 UTC, giusebar approved these changes

2021-05-27 09:23 UTC, georgiablanco approved these changes

2021-05-27 09:24 UTC, merged