Voice test
shadow-robot/common_resources pull request #199
Opened 2021-09-10 12:26 UTC by maxzieba

## Proposed changes

Please explain the changes you made. Add pictures or videos to explain them better if appropriate.

## Checklist

Before posting a PR ensure that from each of the below categories **AT LEAST ONE BOX HAS BEEN CHECKED**. If more than one category is applicable then more can be checked. Also ensure that the proposed changes have been filled out with relevant information for reviewers.

## Tests

- [ ] No tests required to be added. (For small changes that will be tested by CI/CD infrastructure).
- [ ] Added automated tests (if a new class is added (Python or C++), the interface of that class must be unit tested).
- [ ] Manually tested in simulation (if simulation specific or no hardware required to test the functionality). 
- [ ] Manually tested on hardware (if hardware specific or related).

## Documentation

- [ ] No documentation required to be added.
- [ ] Added documentation (For any new feature, explain what it does and how to use it. Write the documentation in a relevant space, e.g. Github, Confluence, etc).
- [ ] Updated documentation (For changes to pre-existing features mentioned in the documentation).

2021-09-14 15:44 UTC, giusebar requested changes

2021-09-14 15:44 UTC, giusebar commented on sr_speech_control/README.md
> +- `command_words_and_feedback` - dicitonary of commands that are allowed to be sent and corresponding sound feedback words
dictionary

2021-09-14 15:44 UTC, giusebar commented on sr_speech_control/README.md
> +- `output_device_name` - the device name on which the voice feedback confirmation should be played
we should probably explain how to retrieve the device name. You are inserting logitech, but where does that come from?

2021-09-14 15:44 UTC, giusebar commented on sr_speech_control/src/sr_speech_control/speech_control.py
> +        rospy.logwarn("Received: {}".format(result))
we should change it to rosinfo if we really want to keep this

2021-09-14 15:44 UTC, giusebar commented on sr_speech_control/src/sr_speech_control/speech_control.py
> +            rospy.logwarn("Understand as : {}".format(command))
same

2021-09-14 15:44 UTC, giusebar commented on sr_speech_control/src/sr_speech_control/speech_control.py
> +        play(audio, output_device_index)
we are still playing if output_device_index is None here. either you add play to the if or set a different device index default

2021-09-14 16:23 UTC, maxzieba commented on sr_speech_control/README.md
> +- `command_words_and_feedback` - dicitonary of commands that are allowed to be sent and corresponding sound feedback words
Corrected

2021-09-14 16:28 UTC, maxzieba commented on sr_speech_control/README.md
> +- `output_device_name` - the device name on which the voice feedback confirmation should be played
Well, the voice feedback is currently only internally so I avoided printing out once again a complete list of output devices (this happens for the microphone already), so the starting time for this feature is faster. To list all available output devices one could run a quick loop like:

p = pyaudio.PyAudio()
for index in range(0, p.get_device_count()):
        rospy.logwarn("{} {}".format(index, p.get_device_info_by_index(index)['name'])

I imagine that for the final product of the hybrid controller we will attach a headset and everything will be played on a single device automatically detected or to be selected in the GUI.

If you want I can add a method to select and explain it as Michał did for the microphone

2021-09-14 16:36 UTC, maxzieba commented on sr_speech_control/src/sr_speech_control/speech_control.py
> +        play(audio, output_device_index)
play uses the default audio device when output_device_index is None (https://people.csail.mit.edu/hubert/pyaudio/docs/#class-stream)

2021-09-15 12:15 UTC, maxzieba commented on sr_speech_control/README.md
> +- `output_device_name` - the device name on which the voice feedback confirmation should be played
Added a info about suggested device name and how to check for those.

2021-09-15 12:15 UTC, maxzieba commented on sr_speech_control/src/sr_speech_control/speech_control.py
> +            rospy.logwarn("Understand as : {}".format(command))
Sure

2021-09-15 12:15 UTC, maxzieba commented on sr_speech_control/src/sr_speech_control/speech_control.py
> +        rospy.logwarn("Received: {}".format(result))
Sure

2021-09-20 13:04 UTC, giusebar submitted a review, later dismissed

2021-09-20 13:04 UTC, giusebar commented on sr_speech_control/src/sr_speech_control/speech_control.py
> +            rospy.logwarn("No default device found. Using first available output device")
we should have this function return the device index and device sample rate, and fill the needed variable

2021-09-20 13:04 UTC, giusebar commented on sr_speech_control/src/sr_speech_control/speech_control.py
> +            return None, None
can you set the variables output_device_index and output_device_rate to None and the beginning and just return them at the end

2021-09-20 13:04 UTC, giusebar commented on sr_speech_control/src/sr_speech_control/speech_control.py
> +        play(audio, output_device_index)
ok

2021-09-20 14:11 UTC, maxzieba commented on sr_speech_control/src/sr_speech_control/speech_control.py
> +            return None, None
Changed

2021-09-21 10:19 UTC, mikramarc requested changes

2021-09-21 10:19 UTC, mikramarc commented on sr_speech_control/src/sr_speech_control/speech_control.py
> +    print("Custom PyDub is not installed. No voice feedback.")
please use ros logging

2021-09-21 10:21 UTC, maxzieba commented on sr_speech_control/src/sr_speech_control/speech_control.py
> +    print("Custom PyDub is not installed. No voice feedback.")
Changed

2021-09-21 11:17 UTC, mikramarc approved these changes

2021-09-22 08:48 UTC, BenStarmerSmith approved these changes

2021-09-22 11:08 UTC, merged