updates
shadow-robot/common_resources pull request #205
Opened 2021-11-02 17:41 UTC by georgiablanco

## Proposed changes

https://shadowrobot.atlassian.net/browse/SRC-6494

## Checklist

Before posting a PR ensure that from each of the below categories **AT LEAST ONE BOX HAS BEEN CHECKED**. If more than one category is applicable then more can be checked. Also ensure that the proposed changes have been filled out with relevant information for reviewers.

## Tests

- [ ] No tests required to be added. (For small changes that will be tested by CI/CD infrastructure).
- [ ] Added automated tests (if a new class is added (Python or C++), the interface of that class must be unit tested).
- [ ] Manually tested in simulation (if simulation specific or no hardware required to test the functionality). 
- [ ] Manually tested on hardware (if hardware specific or related).

## Documentation

- [ ] No documentation required to be added.
- [ ] Added documentation (For any new feature, explain what it does and how to use it. Write the documentation in a relevant space, e.g. Github, Confluence, etc).
- [ ] Updated documentation (For changes to pre-existing features mentioned in the documentation).

2021-11-03 13:38 UTC, biofotis approved these changes

2021-11-03 15:16 UTC, ethanfowler requested changes, later dismissed

2021-11-03 15:16 UTC, ethanfowler commented on sr_ur_arm_calibration_loader/src/sr_ur_arm_calibration_loader/sr_ur_arm_calibration_loader.py
> +# Copyright 2021 Shadow Robot Company Ltd.
Nitpicking, but should be 2020-21.

2021-11-03 15:18 UTC, georgiablanco commented on sr_ur_arm_calibration_loader/src/sr_ur_arm_calibration_loader/sr_ur_arm_calibration_loader.py
> +# Copyright 2021 Shadow Robot Company Ltd.
done

2021-11-04 09:43 UTC, carebare47 approved these changes

2021-11-04 12:28 UTC, biofotis approved these changes

2021-11-04 12:29 UTC, merged