Adding Fraunhofer IPA Rob@work4 mobile base world and collision scene
shadow-robot/common_resources pull request #256
Opened 2023-08-26 10:19 UTC by ethanfowler

## Proposed changes

Adding Fraunhofer IPA Rob@work4 mobile base world and collision scene

## Checklist

Before posting a PR ensure that from each of the below categories **AT LEAST ONE BOX HAS BEEN CHECKED**. If more than one category is applicable then more can be checked. Also ensure that the proposed changes have been filled out with relevant information for reviewers.

## Tests

- [ ] No tests required to be added. (For small changes that will be tested by CI/CD infrastructure).
- [ ] Added/Modified automated and PhantomHand CI tests (if a new class is added (Python or C++), the interface of that class must be unit tested).
- [x] Manually tested in simulation (if simulation specific or no hardware required to test the functionality). 
- [ ] Manually tested on hardware (if hardware specific or related).

## Documentation

- [x] No documentation required to be added.
- [ ] Added documentation (For any new feature, explain what it does and how to use it. Write the documentation in a relevant space, e.g. Github, Confluence, etc).
- [ ] Updated documentation (For changes to pre-existing features mentioned in the documentation).

2023-08-28 15:18 UTC, toliver requested changes

2023-08-28 15:18 UTC, toliver commented on sr_description_common/models/mobile_base/model.config
> +<?xml version="1.0"?>
Should we rename the directory `mobile_base` to a more specific?
Or maybe add a subdirectory `sr_description_common/models/mobile_bases/rob@work4/model.config`

2023-08-28 18:20 UTC, ethanfowler commented on sr_description_common/models/mobile_base/model.config
> +<?xml version="1.0"?>
Not sure how subdirectories would affect model path resolution, so just made names more specific for now, in https://github.com/shadow-robot/common_resources/pull/256/commits/6856cba53067e777fd662aa71c3797b9e877ef5e

2023-08-30 09:47 UTC, jeferal approved these changes

2023-08-30 09:56 UTC, ethanfowler commented
Re-review please @toliver!

2023-09-15 14:23 UTC, toliver approved these changes

2023-09-15 14:24 UTC, merged